version: '3'
services:
  service:
    build: ./movies
    container_name: service
    command: uwsgi --strict --ini /opt/app/uwsgi/uwsgi.ini
    volumes:
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
      - ./.env.db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U app -d movies_database'"]
      interval: 2s
      timeout: 5s
      retries: 120
  nginx:
    image: nginx:1.23.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data:/data:ro
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/mediafiles
    ports:
      - 80:80
    depends_on:
      - service
volumes:
  postgres_data:
  static_volume:
  media_volume:

